### ISSUE TITLE
mender-configure package is outdated when using mender-convert 4.0.2

### ISSUE THREAD

**Issue by dimsanius** [mendersoftware/mender-configure-module#88]
Hello everyone,

First of all, thank you all for producing such an elaborate and irreplaceable product. It has lots of features and potential.

Recently, I checked out `mender-convert` at version `4.0.2`. Within the config file, it is set to use `MENDER_ADDON_CONFIGURE_VERSION=latest`, which I assume has to be `1.1.1` at this moment in time. However, when using `mender-convert` (via docker), it is still using `mender-configure` version `1.1.0`. I tried setting config to `MENDER_ADDON_CONFIGURE_VERSION="1.1.1"` - this leads to `mender-convert` crash as it cannot find version `1.1.1`.

Could you help me out sorting the issue out, please?

Regards,
Dmitrij

PS pardon me if it is not quite a right place for such an issue

**Comment by lluiscampos** [comment]
@dimsanius Thank you for reporting it!

Something is wrong with this package in our repositories. We are looking into it internally :eyes:

**Comment by tranchitella** [comment]
@dimsanius we published `mender-configure` version `1.1.1`.
In the future, please use https://hub.mender.io to report issues.
